apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinitum-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: infinitum-server
  template:
    metadata:
      labels:
        app: infinitum-server
    spec:
      containers:
      - name: infinitum-server
        image: replaceme
        command: ["/bin/sh", "-c"]
        args: ["infinitum-server -socket-io"]
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 3000
          name: api
        env:
          - name: REDIS_HOST
            value: redis.redis
          - name: REDIS_DB
            value: "10"
          - name: RPC_URL
            value: http://10.8.0.2:7076
          - name: DB_HOST
            value: postgres.kubegres          
          - name: DB_PORT
            value: "5432"
          - name: DB_SSLMODE
            value: disable
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: natrium
                key: db_name   
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: infinitum
                key: db_user  
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: infinitum
                key: db_password 
          - name: FCM_API_KEY
            valueFrom:
              secretKeyRef:
                name: infinitum
                key: fcm_api_key
          - name: BPOW_KEY
            valueFrom:
              secretKeyRef:
                name: natrium
                key: bpow_key
          - name: BPOW_URL
            value: http://boompow-service.boompow-next:8080/graphql 
          - name: NODE_WS_URL
            value: ws://10.8.0.2:7078